### ISSUE TITLE
backend에서 사진 받아오는 방식이 필요합니다

### ISSUE THREAD

**Issue by snumath** [swsnu/swpp18-team12#16]
`club_detail` 브랜치에서

백엔드에 `GET api/club/club:id/club_short`를 보냈을 때 profile_image가 이미지 소스 위치로 들어옵니다.

제가 테스트용으로 짜고있는 DB에서는 `/media/club/profile/dba39bd2-3b12-4e10-92ce-0005e35ef5c3.jpg`로 받았습니다.

위치를 따라가보니 백엔드 폴더 그대로 따라가면 원하는 사진이 나옵니다.

이 사진을 프론트로 건내줄 방식이 필요합니다.

아래같은 방식으로 사진이 출력되는지 테스트하고 있습니다.

```HTML
<div *ngIf="imgSrc">
  img Src = {{imgSrc}}
  <img [src]="imgSrc">
</div>
```

**Comment by insung151** [comment]
배포환경에서는 해결되는 문제입니다.

일시적으로 이 문제를 해결하고 싶으시다면 https://docs.djangoproject.com/en/2.1/howto/static-files/#serving-files-uploaded-by-a-user-during-development 를 참고하셔서 urls.py만 조금 수정하면 됩니다.
