### ISSUE TITLE
Dependency Injection Error

### ISSUE THREAD

**Issue by snumath** [swsnu/swpp18-team12#5]
> Unhandled Promise rejection: StaticInjectorError(AppModule) ...

검색해보니 dependency injection 에러라고 합니다
해결 방법으로는 `app.module.ts`에서 `provider`에 service를 넣어주면 된다는데, 해당 service를 넣어줘도 해결이 안 됩니다.
제 지식으로는 해결하기 힘들 것 같아 차후 조교님이나 다른 사람에게 물어봐서 해결하겠습니다.

`sign-in.component.ts`에서 `constructor`에 `AuthenticationService`를 끌어오면 해당 에러가 발생하고, comment처리하면 페이지 렌더는 됩니다.

**Comment by insung151** [comment]
해결 되신건가요?

**Comment by snumath** [comment]
아뇨 내일 다시 알아보려고 합니다

**Comment by insung151** [comment]
App module.ts 에 HttpClientModule이 import에 추가되어있지 않네요

**Comment by snumath** [comment]
해결했습니다. 감사합니다
